const Activities = [
    {
        emoji: '🎃',
        description: 'jack-o-lantern',
        category: 'Activities',
        aliases: ['jack_o_lantern'],
        tags: ['halloween'],
      },
      {
        emoji: '🎄',
        description: 'Christmas tree',
        category: 'Activities',
        aliases: ['christmas_tree'],
      },
      {
        emoji: '🎆',
        description: 'fireworks',
        category: 'Activities',
        aliases: ['fireworks'],
        tags: ['festival', 'celebration'],
      },
      {
        emoji: '🎇',
        description: 'sparkler',
        category: 'Activities',
        aliases: ['sparkler'],
      },
      {
        emoji: '🧨',
        description: 'firecracker',
        category: 'Activities',
        aliases: ['firecracker'],
      },
      {
        emoji: '✨',
        description: 'sparkles',
        category: 'Activities',
        aliases: ['sparkles'],
        tags: ['shiny'],
      },
      {
        emoji: '🎈',
        description: 'balloon',
        category: 'Activities',
        aliases: ['balloon'],
        tags: ['party', 'birthday'],
      },
      {
        emoji: '🎉',
        description: 'party popper',
        category: 'Activities',
        aliases: ['tada'],
        tags: ['hooray', 'party'],
      },
      {
        emoji: '🎊',
        description: 'confetti ball',
        category: 'Activities',
        aliases: ['confetti_ball'],
      },
      {
        emoji: '🎋',
        description: 'tanabata tree',
        category: 'Activities',
        aliases: ['tanabata_tree'],
      },
      {
        emoji: '🎍',
        description: 'pine decoration',
        category: 'Activities',
        aliases: ['bamboo'],
      },
      {
        emoji: '🎎',
        description: 'Japanese dolls',
        category: 'Activities',
        aliases: ['dolls'],
      },
      {
        emoji: '🎏',
        description: 'carp streamer',
        category: 'Activities',
        aliases: ['flags'],
      },
      {
        emoji: '🎐',
        description: 'wind chime',
        category: 'Activities',
        aliases: ['wind_chime'],
      },
      {
        emoji: '🎑',
        description: 'moon viewing ceremony',
        category: 'Activities',
        aliases: ['rice_scene'],
      },
      {
        emoji: '🧧',
        description: 'red envelope',
        category: 'Activities',
        aliases: ['red_envelope'],
      },
      {
        emoji: '🎀',
        description: 'ribbon',
        category: 'Activities',
        aliases: ['ribbon'],
      },
      {
        emoji: '🎁',
        description: 'wrapped gift',
        category: 'Activities',
        aliases: ['gift'],
        tags: ['present', 'birthday', 'christmas'],
      },
      {
        emoji: '🎗️',
        description: 'reminder ribbon',
        category: 'Activities',
        aliases: ['reminder_ribbon'],
      },
      {
        emoji: '🎟️',
        description: 'admission tickets',
        category: 'Activities',
        aliases: ['tickets'],
      },
      {
        emoji: '🎫',
        description: 'ticket',
        category: 'Activities',
        aliases: ['ticket'],
      },
      {
        emoji: '🎖️',
        description: 'military medal',
        category: 'Activities',
        aliases: ['medal_military'],
      },
      {
        emoji: '🏆',
        description: 'trophy',
        category: 'Activities',
        aliases: ['trophy'],
        tags: ['award', 'contest', 'winner'],
      },
      {
        emoji: '🏅',
        description: 'sports medal',
        category: 'Activities',
        aliases: ['medal_sports'],
        tags: ['gold', 'winner'],
      },
      {
        emoji: '🥇',
        description: '1st place medal',
        category: 'Activities',
        aliases: ['1st_place_medal'],
        tags: ['gold'],
      },
      {
        emoji: '🥈',
        description: '2nd place medal',
        category: 'Activities',
        aliases: ['2nd_place_medal'],
        tags: ['silver'],
      },
      {
        emoji: '🥉',
        description: '3rd place medal',
        category: 'Activities',
        aliases: ['3rd_place_medal'],
        tags: ['bronze'],
      },
      {
        emoji: '⚽',
        description: 'soccer ball',
        category: 'Activities',
        aliases: ['soccer'],
        tags: ['sports'],
      },
      {
        emoji: '⚾',
        description: 'baseball',
        category: 'Activities',
        aliases: ['baseball'],
        tags: ['sports'],
      },
      {
        emoji: '🥎',
        description: 'softball',
        category: 'Activities',
        aliases: ['softball'],
      },
      {
        emoji: '🏀',
        description: 'basketball',
        category: 'Activities',
        aliases: ['basketball'],
        tags: ['sports'],
      },
      {
        emoji: '🏐',
        description: 'volleyball',
        category: 'Activities',
        aliases: ['volleyball'],
      },
      {
        emoji: '🏈',
        description: 'american football',
        category: 'Activities',
        aliases: ['football'],
        tags: ['sports'],
      },
      {
        emoji: '🏉',
        description: 'rugby football',
        category: 'Activities',
        aliases: ['rugby_football'],
      },
      {
        emoji: '🎾',
        description: 'tennis',
        category: 'Activities',
        aliases: ['tennis'],
        tags: ['sports'],
      },
      {
        emoji: '🥏',
        description: 'flying disc',
        category: 'Activities',
        aliases: ['flying_disc'],
      },
      {
        emoji: '🎳',
        description: 'bowling',
        category: 'Activities',
        aliases: ['bowling'],
      },
      {
        emoji: '🏏',
        description: 'cricket game',
        category: 'Activities',
        aliases: ['cricket_game'],
      },
      {
        emoji: '🏑',
        description: 'field hockey',
        category: 'Activities',
        aliases: ['field_hockey'],
      },
      {
        emoji: '🏒',
        description: 'ice hockey',
        category: 'Activities',
        aliases: ['ice_hockey'],
      },
      {
        emoji: '🥍',
        description: 'lacrosse',
        category: 'Activities',
        aliases: ['lacrosse'],
      },
      {
        emoji: '🏓',
        description: 'ping pong',
        category: 'Activities',
        aliases: ['ping_pong'],
      },
      {
        emoji: '🏸',
        description: 'badminton',
        category: 'Activities',
        aliases: ['badminton'],
      },
      {
        emoji: '🥊',
        description: 'boxing glove',
        category: 'Activities',
        aliases: ['boxing_glove'],
      },
      {
        emoji: '🥋',
        description: 'martial arts uniform',
        category: 'Activities',
        aliases: ['martial_arts_uniform'],
      },
      {
        emoji: '🥅',
        description: 'goal net',
        category: 'Activities',
        aliases: ['goal_net'],
      },
      {
        emoji: '⛳',
        description: 'flag in hole',
        category: 'Activities',
        aliases: ['golf'],
      },
      {
        emoji: '⛸️',
        description: 'ice skate',
        category: 'Activities',
        aliases: ['ice_skate'],
        tags: ['skating'],
      },
      {
        emoji: '🎣',
        description: 'fishing pole',
        category: 'Activities',
        aliases: ['fishing_pole_and_fish'],
      },
      {
        emoji: '🤿',
        description: 'diving mask',
        category: 'Activities',
        aliases: ['diving_mask'],
      },
      {
        emoji: '🎽',
        description: 'running shirt',
        category: 'Activities',
        aliases: ['running_shirt_with_sash'],
        tags: ['marathon'],
      },
      {
        emoji: '🎿',
        description: 'skis',
        category: 'Activities',
        aliases: ['ski'],
      },
      {
        emoji: '🛷',
        description: 'sled',
        category: 'Activities',
        aliases: ['sled'],
      },
      {
        emoji: '🥌',
        description: 'curling stone',
        category: 'Activities',
        aliases: ['curling_stone'],
      },
      {
        emoji: '🎯',
        description: 'bullseye',
        category: 'Activities',
        aliases: ['dart'],
        tags: ['target'],
      },
      {
        emoji: '🪀',
        description: 'yo-yo',
        category: 'Activities',
        aliases: ['yo_yo'],
      },
      {
        emoji: '🪁',
        description: 'kite',
        category: 'Activities',
        aliases: ['kite'],
      },
      {
        emoji: '🎱',
        description: 'pool 8 ball',
        category: 'Activities',
        aliases: ['8ball'],
        tags: ['pool', 'billiards'],
      },
      {
        emoji: '🔮',
        description: 'crystal ball',
        category: 'Activities',
        aliases: ['crystal_ball'],
        tags: ['fortune'],
      },
      {
        emoji: '🪄',
        description: 'magic wand',
        category: 'Activities',
        aliases: ['magic_wand'],
      },
      {
        emoji: '🧿',
        description: 'nazar amulet',
        category: 'Activities',
        aliases: ['nazar_amulet'],
      },
      {
        emoji: '🎮',
        description: 'video game',
        category: 'Activities',
        aliases: ['video_game'],
        tags: ['play', 'controller', 'console'],
      },
      {
        emoji: '🕹️',
        description: 'joystick',
        category: 'Activities',
        aliases: ['joystick'],
      },
      {
        emoji: '🎰',
        description: 'slot machine',
        category: 'Activities',
        aliases: ['slot_machine'],
      },
      {
        emoji: '🎲',
        description: 'game die',
        category: 'Activities',
        aliases: ['game_die'],
        tags: ['dice', 'gambling'],
      },
      {
        emoji: '🧩',
        description: 'puzzle piece',
        category: 'Activities',
        aliases: ['jigsaw'],
      },
      {
        emoji: '🧸',
        description: 'teddy bear',
        category: 'Activities',
        aliases: ['teddy_bear'],
      },
      {
        emoji: '🪅',
        description: 'piñata',
        category: 'Activities',
        aliases: ['pinata'],
      },
      {
        emoji: '🪆',
        description: 'nesting dolls',
        category: 'Activities',
        aliases: ['nesting_dolls'],
      },
      {
        emoji: '♠️',
        description: 'spade suit',
        category: 'Activities',
        aliases: ['spades'],
      },
      {
        emoji: '♥️',
        description: 'heart suit',
        category: 'Activities',
        aliases: ['hearts'],
      },
      {
        emoji: '♦️',
        description: 'diamond suit',
        category: 'Activities',
        aliases: ['diamonds'],
      },
      {
        emoji: '♣️',
        description: 'club suit',
        category: 'Activities',
        aliases: ['clubs'],
      },
      {
        emoji: '♟️',
        description: 'chess pawn',
        category: 'Activities',
        aliases: ['chess_pawn'],
      },
      {
        emoji: '🃏',
        description: 'joker',
        category: 'Activities',
        aliases: ['black_joker'],
      },
      {
        emoji: '🀄',
        description: 'mahjong red dragon',
        category: 'Activities',
        aliases: ['mahjong'],
      },
      {
        emoji: '🎴',
        description: 'flower playing cards',
        category: 'Activities',
        aliases: ['flower_playing_cards'],
      },
      {
        emoji: '🎭',
        description: 'performing arts',
        category: 'Activities',
        aliases: ['performing_arts'],
        tags: ['theater', 'drama'],
      },
      {
        emoji: '🖼️',
        description: 'framed picture',
        category: 'Activities',
        aliases: ['framed_picture'],
      },
      {
        emoji: '🎨',
        description: 'artist palette',
        category: 'Activities',
        aliases: ['art'],
        tags: ['design', 'paint'],
      },
      {
        emoji: '🧵',
        description: 'thread',
        category: 'Activities',
        aliases: ['thread'],
      },
      {
        emoji: '🪡',
        description: 'sewing needle',
        category: 'Activities',
        aliases: ['sewing_needle'],
      },
      {
        emoji: '🧶',
        description: 'yarn',
        category: 'Activities',
        aliases: ['yarn'],
      },
      {
        emoji: '🪢',
        description: 'knot',
        category: 'Activities',
        aliases: ['knot'],
      },

];

export default Activities;