const Nature = [
    {
        emoji: '🐵',
        description: 'monkey face',
        category: 'Animals & Nature',
        aliases: ['monkey_face'],
      },
      {
        emoji: '🐒',
        description: 'monkey',
        category: 'Animals & Nature',
        aliases: ['monkey'],
      },
      {
        emoji: '🦍',
        description: 'gorilla',
        category: 'Animals & Nature',
        aliases: ['gorilla'],
      },
      {
        emoji: '🦧',
        description: 'orangutan',
        category: 'Animals & Nature',
        aliases: ['orangutan'],
      },
      {
        emoji: '🐶',
        description: 'dog face',
        category: 'Animals & Nature',
        aliases: ['dog'],
        tags: ['pet'],
      },
      {
        emoji: '🐕',
        description: 'dog',
        category: 'Animals & Nature',
        aliases: ['dog2'],
      },
      {
        emoji: '🦮',
        description: 'guide dog',
        category: 'Animals & Nature',
        aliases: ['guide_dog'],
      },
      {
        emoji: '🐕‍🦺',
        description: 'service dog',
        category: 'Animals & Nature',
        aliases: ['service_dog'],
      },
      {
        emoji: '🐩',
        description: 'poodle',
        category: 'Animals & Nature',
        aliases: ['poodle'],
        tags: ['dog'],
      },
      {
        emoji: '🐺',
        description: 'wolf',
        category: 'Animals & Nature',
        aliases: ['wolf'],
      },
      {
        emoji: '🦊',
        description: 'fox',
        category: 'Animals & Nature',
        aliases: ['fox_face'],
      },
      {
        emoji: '🦝',
        description: 'raccoon',
        category: 'Animals & Nature',
        aliases: ['raccoon'],
      },
      {
        emoji: '🐱',
        description: 'cat face',
        category: 'Animals & Nature',
        aliases: ['cat'],
        tags: ['pet'],
      },
      {
        emoji: '🐈',
        description: 'cat',
        category: 'Animals & Nature',
        aliases: ['cat2'],
      },
      {
        emoji: '🐈‍⬛',
        description: 'black cat',
        category: 'Animals & Nature',
        aliases: ['black_cat'],
      },
      {
        emoji: '🦁',
        description: 'lion',
        category: 'Animals & Nature',
        aliases: ['lion'],
      },
      {
        emoji: '🐯',
        description: 'tiger face',
        category: 'Animals & Nature',
        aliases: ['tiger'],
      },
      {
        emoji: '🐅',
        description: 'tiger',
        category: 'Animals & Nature',
        aliases: ['tiger2'],
      },
      {
        emoji: '🐆',
        description: 'leopard',
        category: 'Animals & Nature',
        aliases: ['leopard'],
      },
      {
        emoji: '🐴',
        description: 'horse face',
        category: 'Animals & Nature',
        aliases: ['horse'],
      },
      {
        emoji: '🐎',
        description: 'horse',
        category: 'Animals & Nature',
        aliases: ['racehorse'],
        tags: ['speed'],
      },
      {
        emoji: '🦄',
        description: 'unicorn',
        category: 'Animals & Nature',
        aliases: ['unicorn'],
      },
      {
        emoji: '🦓',
        description: 'zebra',
        category: 'Animals & Nature',
        aliases: ['zebra'],
      },
      {
        emoji: '🦌',
        description: 'deer',
        category: 'Animals & Nature',
        aliases: ['deer'],
      },
      {
        emoji: '🦬',
        description: 'bison',
        category: 'Animals & Nature',
        aliases: ['bison'],
      },
      {
        emoji: '🐮',
        description: 'cow face',
        category: 'Animals & Nature',
        aliases: ['cow'],
      },
      {
        emoji: '🐂',
        description: 'ox',
        category: 'Animals & Nature',
        aliases: ['ox'],
      },
      {
        emoji: '🐃',
        description: 'water buffalo',
        category: 'Animals & Nature',
        aliases: ['water_buffalo'],
      },
      {
        emoji: '🐄',
        description: 'cow',
        category: 'Animals & Nature',
        aliases: ['cow2'],
      },
      {
        emoji: '🐷',
        description: 'pig face',
        category: 'Animals & Nature',
        aliases: ['pig'],
      },
      {
        emoji: '🐖',
        description: 'pig',
        category: 'Animals & Nature',
        aliases: ['pig2'],
      },
      {
        emoji: '🐗',
        description: 'boar',
        category: 'Animals & Nature',
        aliases: ['boar'],
      },
      {
        emoji: '🐽',
        description: 'pig nose',
        category: 'Animals & Nature',
        aliases: ['pig_nose'],
      },
      {
        emoji: '🐏',
        description: 'ram',
        category: 'Animals & Nature',
        aliases: ['ram'],
      },
      {
        emoji: '🐑',
        description: 'ewe',
        category: 'Animals & Nature',
        aliases: ['sheep'],
      },
      {
        emoji: '🐐',
        description: 'goat',
        category: 'Animals & Nature',
        aliases: ['goat'],
      },
      {
        emoji: '🐪',
        description: 'camel',
        category: 'Animals & Nature',
        aliases: ['dromedary_camel'],
        tags: ['desert'],
      },
      {
        emoji: '🐫',
        description: 'two-hump camel',
        category: 'Animals & Nature',
        aliases: ['camel'],
      },
      {
        emoji: '🦙',
        description: 'llama',
        category: 'Animals & Nature',
        aliases: ['llama'],
      },
      {
        emoji: '🦒',
        description: 'giraffe',
        category: 'Animals & Nature',
        aliases: ['giraffe'],
      },
      {
        emoji: '🐘',
        description: 'elephant',
        category: 'Animals & Nature',
        aliases: ['elephant'],
      },
      {
        emoji: '🦣',
        description: 'mammoth',
        category: 'Animals & Nature',
        aliases: ['mammoth'],
      },
      {
        emoji: '🦏',
        description: 'rhinoceros',
        category: 'Animals & Nature',
        aliases: ['rhinoceros'],
      },
      {
        emoji: '🦛',
        description: 'hippopotamus',
        category: 'Animals & Nature',
        aliases: ['hippopotamus'],
      },
      {
        emoji: '🐭',
        description: 'mouse face',
        category: 'Animals & Nature',
        aliases: ['mouse'],
      },
      {
        emoji: '🐁',
        description: 'mouse',
        category: 'Animals & Nature',
        aliases: ['mouse2'],
      },
      {
        emoji: '🐀',
        description: 'rat',
        category: 'Animals & Nature',
        aliases: ['rat'],
      },
      {
        emoji: '🐹',
        description: 'hamster',
        category: 'Animals & Nature',
        aliases: ['hamster'],
        tags: ['pet'],
      },
      {
        emoji: '🐰',
        description: 'rabbit face',
        category: 'Animals & Nature',
        aliases: ['rabbit'],
        tags: ['bunny'],
      },
      {
        emoji: '🐇',
        description: 'rabbit',
        category: 'Animals & Nature',
        aliases: ['rabbit2'],
      },
      {
        emoji: '🐿️',
        description: 'chipmunk',
        category: 'Animals & Nature',
        aliases: ['chipmunk'],
      },
      {
        emoji: '🦫',
        description: 'beaver',
        category: 'Animals & Nature',
        aliases: ['beaver'],
      },
      {
        emoji: '🦔',
        description: 'hedgehog',
        category: 'Animals & Nature',
        aliases: ['hedgehog'],
      },
      {
        emoji: '🦇',
        description: 'bat',
        category: 'Animals & Nature',
        aliases: ['bat'],
      },
      {
        emoji: '🐻',
        description: 'bear',
        category: 'Animals & Nature',
        aliases: ['bear'],
      },
      {
        emoji: '🐻‍❄️',
        description: 'polar bear',
        category: 'Animals & Nature',
        aliases: ['polar_bear'],
      },
      {
        emoji: '🐨',
        description: 'koala',
        category: 'Animals & Nature',
        aliases: ['koala'],
      },
      {
        emoji: '🐼',
        description: 'panda',
        category: 'Animals & Nature',
        aliases: ['panda_face'],
      },
      {
        emoji: '🦥',
        description: 'sloth',
        category: 'Animals & Nature',
        aliases: ['sloth'],
      },
      {
        emoji: '🦦',
        description: 'otter',
        category: 'Animals & Nature',
        aliases: ['otter'],
      },
      {
        emoji: '🦨',
        description: 'skunk',
        category: 'Animals & Nature',
        aliases: ['skunk'],
      },
      {
        emoji: '🦘',
        description: 'kangaroo',
        category: 'Animals & Nature',
        aliases: ['kangaroo'],
      },
      {
        emoji: '🦡',
        description: 'badger',
        category: 'Animals & Nature',
        aliases: ['badger'],
      },
      {
        emoji: '🐾',
        description: 'paw prints',
        category: 'Animals & Nature',
        aliases: ['feet', 'paw_prints'],
      },
      {
        emoji: '🦃',
        description: 'turkey',
        category: 'Animals & Nature',
        aliases: ['turkey'],
        tags: ['thanksgiving'],
      },
      {
        emoji: '🐔',
        description: 'chicken',
        category: 'Animals & Nature',
        aliases: ['chicken'],
      },
      {
        emoji: '🐓',
        description: 'rooster',
        category: 'Animals & Nature',
        aliases: ['rooster'],
      },
      {
        emoji: '🐣',
        description: 'hatching chick',
        category: 'Animals & Nature',
        aliases: ['hatching_chick'],
      },
      {
        emoji: '🐤',
        description: 'baby chick',
        category: 'Animals & Nature',
        aliases: ['baby_chick'],
      },
      {
        emoji: '🐥',
        description: 'front-facing baby chick',
        category: 'Animals & Nature',
        aliases: ['hatched_chick'],
      },
      {
        emoji: '🐦',
        description: 'bird',
        category: 'Animals & Nature',
        aliases: ['bird'],
      },
      {
        emoji: '🐧',
        description: 'penguin',
        category: 'Animals & Nature',
        aliases: ['penguin'],
      },
      {
        emoji: '🕊️',
        description: 'dove',
        category: 'Animals & Nature',
        aliases: ['dove'],
        tags: ['peace'],
      },
      {
        emoji: '🦅',
        description: 'eagle',
        category: 'Animals & Nature',
        aliases: ['eagle'],
      },
      {
        emoji: '🦆',
        description: 'duck',
        category: 'Animals & Nature',
        aliases: ['duck'],
      },
      {
        emoji: '🦢',
        description: 'swan',
        category: 'Animals & Nature',
        aliases: ['swan'],
      },
      {
        emoji: '🦉',
        description: 'owl',
        category: 'Animals & Nature',
        aliases: ['owl'],
      },
      {
        emoji: '🦤',
        description: 'dodo',
        category: 'Animals & Nature',
        aliases: ['dodo'],
      },
      {
        emoji: '🪶',
        description: 'feather',
        category: 'Animals & Nature',
        aliases: ['feather'],
      },
      {
        emoji: '🦩',
        description: 'flamingo',
        category: 'Animals & Nature',
        aliases: ['flamingo'],
      },
      {
        emoji: '🦚',
        description: 'peacock',
        category: 'Animals & Nature',
        aliases: ['peacock'],
      },
      {
        emoji: '🦜',
        description: 'parrot',
        category: 'Animals & Nature',
        aliases: ['parrot'],
      },
      {
        emoji: '🐸',
        description: 'frog',
        category: 'Animals & Nature',
        aliases: ['frog'],
      },
      {
        emoji: '🐊',
        description: 'crocodile',
        category: 'Animals & Nature',
        aliases: ['crocodile'],
      },
      {
        emoji: '🐢',
        description: 'turtle',
        category: 'Animals & Nature',
        aliases: ['turtle'],
        tags: ['slow'],
      },
      {
        emoji: '🦎',
        description: 'lizard',
        category: 'Animals & Nature',
        aliases: ['lizard'],
      },
      {
        emoji: '🐍',
        description: 'snake',
        category: 'Animals & Nature',
        aliases: ['snake'],
      },
      {
        emoji: '🐲',
        description: 'dragon face',
        category: 'Animals & Nature',
        aliases: ['dragon_face'],
      },
      {
        emoji: '🐉',
        description: 'dragon',
        category: 'Animals & Nature',
        aliases: ['dragon'],
      },
      {
        emoji: '🦕',
        description: 'sauropod',
        category: 'Animals & Nature',
        aliases: ['sauropod'],
        tags: ['dinosaur'],
      },
      {
        emoji: '🦖',
        description: 'T-Rex',
        category: 'Animals & Nature',
        aliases: ['t-rex'],
        tags: ['dinosaur'],
      },
      {
        emoji: '🐳',
        description: 'spouting whale',
        category: 'Animals & Nature',
        aliases: ['whale'],
        tags: ['sea'],
      },
      {
        emoji: '🐋',
        description: 'whale',
        category: 'Animals & Nature',
        aliases: ['whale2'],
      },
      {
        emoji: '🐬',
        description: 'dolphin',
        category: 'Animals & Nature',
        aliases: ['dolphin', 'flipper'],
      },
      {
        emoji: '🦭',
        description: 'seal',
        category: 'Animals & Nature',
        aliases: ['seal'],
      },
      {
        emoji: '🐟',
        description: 'fish',
        category: 'Animals & Nature',
        aliases: ['fish'],
      },
      {
        emoji: '🐠',
        description: 'tropical fish',
        category: 'Animals & Nature',
        aliases: ['tropical_fish'],
      },
      {
        emoji: '🐡',
        description: 'blowfish',
        category: 'Animals & Nature',
        aliases: ['blowfish'],
      },
      {
        emoji: '🦈',
        description: 'shark',
        category: 'Animals & Nature',
        aliases: ['shark'],
      },
      {
        emoji: '🐙',
        description: 'octopus',
        category: 'Animals & Nature',
        aliases: ['octopus'],
      },
      {
        emoji: '🐚',
        description: 'spiral shell',
        category: 'Animals & Nature',
        aliases: ['shell'],
        tags: ['sea', 'beach'],
      },
      {
        emoji: '🐌',
        description: 'snail',
        category: 'Animals & Nature',
        aliases: ['snail'],
        tags: ['slow'],
      },
      {
        emoji: '🦋',
        description: 'butterfly',
        category: 'Animals & Nature',
        aliases: ['butterfly'],
      },
      {
        emoji: '🐛',
        description: 'bug',
        category: 'Animals & Nature',
        aliases: ['bug'],
      },
      {
        emoji: '🐜',
        description: 'ant',
        category: 'Animals & Nature',
        aliases: ['ant'],
      },
      {
        emoji: '🐝',
        description: 'honeybee',
        category: 'Animals & Nature',
        aliases: ['bee', 'honeybee'],
      },
      {
        emoji: '🪲',
        description: 'beetle',
        category: 'Animals & Nature',
        aliases: ['beetle'],
      },
      {
        emoji: '🐞',
        description: 'lady beetle',
        category: 'Animals & Nature',
        aliases: ['lady_beetle'],
        tags: ['bug'],
      },
      {
        emoji: '🦗',
        description: 'cricket',
        category: 'Animals & Nature',
        aliases: ['cricket'],
      },
      {
        emoji: '🪳',
        description: 'cockroach',
        category: 'Animals & Nature',
        aliases: ['cockroach'],
      },
      {
        emoji: '🕷️',
        description: 'spider',
        category: 'Animals & Nature',
        aliases: ['spider'],
      },
      {
        emoji: '🕸️',
        description: 'spider web',
        category: 'Animals & Nature',
        aliases: ['spider_web'],
      },
      {
        emoji: '🦂',
        description: 'scorpion',
        category: 'Animals & Nature',
        aliases: ['scorpion'],
      },
      {
        emoji: '🦟',
        description: 'mosquito',
        category: 'Animals & Nature',
        aliases: ['mosquito'],
      },
      {
        emoji: '🪰',
        description: 'fly',
        category: 'Animals & Nature',
        aliases: ['fly'],
      },
      {
        emoji: '🪱',
        description: 'worm',
        category: 'Animals & Nature',
        aliases: ['worm'],
      },
      {
        emoji: '🦠',
        description: 'microbe',
        category: 'Animals & Nature',
        aliases: ['microbe'],
        tags: ['germ'],
      },
      {
        emoji: '💐',
        description: 'bouquet',
        category: 'Animals & Nature',
        aliases: ['bouquet'],
        tags: ['flowers'],
      },
      {
        emoji: '🌸',
        description: 'cherry blossom',
        category: 'Animals & Nature',
        aliases: ['cherry_blossom'],
        tags: ['flower', 'spring'],
      },
      {
        emoji: '💮',
        description: 'white flower',
        category: 'Animals & Nature',
        aliases: ['white_flower'],
      },
      {
        emoji: '🏵️',
        description: 'rosette',
        category: 'Animals & Nature',
        aliases: ['rosette'],
      },
      {
        emoji: '🌹',
        description: 'rose',
        category: 'Animals & Nature',
        aliases: ['rose'],
        tags: ['flower'],
      },
      {
        emoji: '🥀',
        description: 'wilted flower',
        category: 'Animals & Nature',
        aliases: ['wilted_flower'],
      },
      {
        emoji: '🌺',
        description: 'hibiscus',
        category: 'Animals & Nature',
        aliases: ['hibiscus'],
      },
      {
        emoji: '🌻',
        description: 'sunflower',
        category: 'Animals & Nature',
        aliases: ['sunflower'],
      },
      {
        emoji: '🌼',
        description: 'blossom',
        category: 'Animals & Nature',
        aliases: ['blossom'],
      },
      {
        emoji: '🌷',
        description: 'tulip',
        category: 'Animals & Nature',
        aliases: ['tulip'],
        tags: ['flower'],
      },
      {
        emoji: '🌱',
        description: 'seedling',
        category: 'Animals & Nature',
        aliases: ['seedling'],
        tags: ['plant'],
      },
      {
        emoji: '🪴',
        description: 'potted plant',
        category: 'Animals & Nature',
        aliases: ['potted_plant'],
      },
      {
        emoji: '🌲',
        description: 'evergreen tree',
        category: 'Animals & Nature',
        aliases: ['evergreen_tree'],
        tags: ['wood'],
      },
      {
        emoji: '🌳',
        description: 'deciduous tree',
        category: 'Animals & Nature',
        aliases: ['deciduous_tree'],
        tags: ['wood'],
      },
      {
        emoji: '🌴',
        description: 'palm tree',
        category: 'Animals & Nature',
        aliases: ['palm_tree'],
      },
      {
        emoji: '🌵',
        description: 'cactus',
        category: 'Animals & Nature',
        aliases: ['cactus'],
      },
      {
        emoji: '🌾',
        description: 'sheaf of rice',
        category: 'Animals & Nature',
        aliases: ['ear_of_rice'],
      },
      {
        emoji: '🌿',
        description: 'herb',
        category: 'Animals & Nature',
        aliases: ['herb'],
      },
      {
        emoji: '☘️',
        description: 'shamrock',
        category: 'Animals & Nature',
        aliases: ['shamrock'],
      },
      {
        emoji: '🍀',
        description: 'four leaf clover',
        category: 'Animals & Nature',
        aliases: ['four_leaf_clover'],
        tags: ['luck'],
      },
      {
        emoji: '🍁',
        description: 'maple leaf',
        category: 'Animals & Nature',
        aliases: ['maple_leaf'],
        tags: ['canada'],
      },
      {
        emoji: '🍂',
        description: 'fallen leaf',
        category: 'Animals & Nature',
        aliases: ['fallen_leaf'],
        tags: ['autumn'],
      },
      {
        emoji: '🍃',
        description: 'leaf fluttering in wind',
        category: 'Animals & Nature',
        aliases: ['leaves'],
        tags: ['leaf'],
      },
];

export default Nature;