const Food = [
    {
        emoji: '🍇',
        description: 'grapes',
        category: 'Food & Drink',
        aliases: ['grapes'],
      },
      {
        emoji: '🍈',
        description: 'melon',
        category: 'Food & Drink',
        aliases: ['melon'],
      },
      {
        emoji: '🍉',
        description: 'watermelon',
        category: 'Food & Drink',
        aliases: ['watermelon'],
      },
      {
        emoji: '🍊',
        description: 'tangerine',
        category: 'Food & Drink',
        aliases: ['tangerine', 'orange', 'mandarin'],
      },
      {
        emoji: '🍋',
        description: 'lemon',
        category: 'Food & Drink',
        aliases: ['lemon'],
      },
      {
        emoji: '🍌',
        description: 'banana',
        category: 'Food & Drink',
        aliases: ['banana'],
        tags: ['fruit'],
      },
      {
        emoji: '🍍',
        description: 'pineapple',
        category: 'Food & Drink',
        aliases: ['pineapple'],
      },
      {
        emoji: '🥭',
        description: 'mango',
        category: 'Food & Drink',
        aliases: ['mango'],
      },
      {
        emoji: '🍎',
        description: 'red apple',
        category: 'Food & Drink',
        aliases: ['apple'],
      },
      {
        emoji: '🍏',
        description: 'green apple',
        category: 'Food & Drink',
        aliases: ['green_apple'],
        tags: ['fruit'],
      },
      {
        emoji: '🍐',
        description: 'pear',
        category: 'Food & Drink',
        aliases: ['pear'],
      },
      {
        emoji: '🍑',
        description: 'peach',
        category: 'Food & Drink',
        aliases: ['peach'],
      },
      {
        emoji: '🍒',
        description: 'cherries',
        category: 'Food & Drink',
        aliases: ['cherries'],
        tags: ['fruit'],
      },
      {
        emoji: '🍓',
        description: 'strawberry',
        category: 'Food & Drink',
        aliases: ['strawberry'],
        tags: ['fruit'],
      },
      {
        emoji: '🫐',
        description: 'blueberries',
        category: 'Food & Drink',
        aliases: ['blueberries'],
      },
      {
        emoji: '🥝',
        description: 'kiwi fruit',
        category: 'Food & Drink',
        aliases: ['kiwi_fruit'],
      },
      {
        emoji: '🍅',
        description: 'tomato',
        category: 'Food & Drink',
        aliases: ['tomato'],
      },
      {
        emoji: '🫒',
        description: 'olive',
        category: 'Food & Drink',
        aliases: ['olive'],
      },
      {
        emoji: '🥥',
        description: 'coconut',
        category: 'Food & Drink',
        aliases: ['coconut'],
      },
      {
        emoji: '🥑',
        description: 'avocado',
        category: 'Food & Drink',
        aliases: ['avocado'],
      },
      {
        emoji: '🍆',
        description: 'eggplant',
        category: 'Food & Drink',
        aliases: ['eggplant'],
        tags: ['aubergine'],
      },
      {
        emoji: '🥔',
        description: 'potato',
        category: 'Food & Drink',
        aliases: ['potato'],
      },
      {
        emoji: '🥕',
        description: 'carrot',
        category: 'Food & Drink',
        aliases: ['carrot'],
      },
      {
        emoji: '🌽',
        description: 'ear of corn',
        category: 'Food & Drink',
        aliases: ['corn'],
      },
      {
        emoji: '🌶️',
        description: 'hot pepper',
        category: 'Food & Drink',
        aliases: ['hot_pepper'],
        tags: ['spicy'],
      },
      {
        emoji: '🫑',
        description: 'bell pepper',
        category: 'Food & Drink',
        aliases: ['bell_pepper'],
      },
      {
        emoji: '🥒',
        description: 'cucumber',
        category: 'Food & Drink',
        aliases: ['cucumber'],
      },
      {
        emoji: '🥬',
        description: 'leafy green',
        category: 'Food & Drink',
        aliases: ['leafy_green'],
      },
      {
        emoji: '🥦',
        description: 'broccoli',
        category: 'Food & Drink',
        aliases: ['broccoli'],
      },
      {
        emoji: '🧄',
        description: 'garlic',
        category: 'Food & Drink',
        aliases: ['garlic'],
      },
      {
        emoji: '🧅',
        description: 'onion',
        category: 'Food & Drink',
        aliases: ['onion'],
      },
      {
        emoji: '🍄',
        description: 'mushroom',
        category: 'Food & Drink',
        aliases: ['mushroom'],
      },
      {
        emoji: '🥜',
        description: 'peanuts',
        category: 'Food & Drink',
        aliases: ['peanuts'],
      },
      {
        emoji: '🌰',
        description: 'chestnut',
        category: 'Food & Drink',
        aliases: ['chestnut'],
      },
      {
        emoji: '🍞',
        description: 'bread',
        category: 'Food & Drink',
        aliases: ['bread'],
        tags: ['toast'],
      },
      {
        emoji: '🥐',
        description: 'croissant',
        category: 'Food & Drink',
        aliases: ['croissant'],
      },
      {
        emoji: '🥖',
        description: 'baguette bread',
        category: 'Food & Drink',
        aliases: ['baguette_bread'],
      },
      {
        emoji: '🫓',
        description: 'flatbread',
        category: 'Food & Drink',
        aliases: ['flatbread'],
      },
      {
        emoji: '🥨',
        description: 'pretzel',
        category: 'Food & Drink',
        aliases: ['pretzel'],
      },
      {
        emoji: '🥯',
        description: 'bagel',
        category: 'Food & Drink',
        aliases: ['bagel'],
      },
      {
        emoji: '🥞',
        description: 'pancakes',
        category: 'Food & Drink',
        aliases: ['pancakes'],
      },
      {
        emoji: '🧇',
        description: 'waffle',
        category: 'Food & Drink',
        aliases: ['waffle'],
      },
      {
        emoji: '🧀',
        description: 'cheese wedge',
        category: 'Food & Drink',
        aliases: ['cheese'],
      },
      {
        emoji: '🍖',
        description: 'meat on bone',
        category: 'Food & Drink',
        aliases: ['meat_on_bone'],
      },
      {
        emoji: '🍗',
        description: 'poultry leg',
        category: 'Food & Drink',
        aliases: ['poultry_leg'],
        tags: ['meat', 'chicken'],
      },
      {
        emoji: '🥩',
        description: 'cut of meat',
        category: 'Food & Drink',
        aliases: ['cut_of_meat'],
      },
      {
        emoji: '🥓',
        description: 'bacon',
        category: 'Food & Drink',
        aliases: ['bacon'],
      },
      {
        emoji: '🍔',
        description: 'hamburger',
        category: 'Food & Drink',
        aliases: ['hamburger'],
        tags: ['burger'],
      },
      {
        emoji: '🍟',
        description: 'french fries',
        category: 'Food & Drink',
        aliases: ['fries'],
      },
      {
        emoji: '🍕',
        description: 'pizza',
        category: 'Food & Drink',
        aliases: ['pizza'],
      },
      {
        emoji: '🌭',
        description: 'hot dog',
        category: 'Food & Drink',
        aliases: ['hotdog'],
      },
      {
        emoji: '🥪',
        description: 'sandwich',
        category: 'Food & Drink',
        aliases: ['sandwich'],
      },
      {
        emoji: '🌮',
        description: 'taco',
        category: 'Food & Drink',
        aliases: ['taco'],
      },
      {
        emoji: '🌯',
        description: 'burrito',
        category: 'Food & Drink',
        aliases: ['burrito'],
      },
      {
        emoji: '🫔',
        description: 'tamale',
        category: 'Food & Drink',
        aliases: ['tamale'],
      },
      {
        emoji: '🥙',
        description: 'stuffed flatbread',
        category: 'Food & Drink',
        aliases: ['stuffed_flatbread'],
      },
      {
        emoji: '🧆',
        description: 'falafel',
        category: 'Food & Drink',
        aliases: ['falafel'],
      },
      {
        emoji: '🥚',
        description: 'egg',
        category: 'Food & Drink',
        aliases: ['egg'],
      },
      {
        emoji: '🍳',
        description: 'cooking',
        category: 'Food & Drink',
        aliases: ['fried_egg'],
        tags: ['breakfast'],
      },
      {
        emoji: '🥘',
        description: 'shallow pan of food',
        category: 'Food & Drink',
        aliases: ['shallow_pan_of_food'],
        tags: ['paella', 'curry'],
      },
      {
        emoji: '🍲',
        description: 'pot of food',
        category: 'Food & Drink',
        aliases: ['stew'],
      },
      {
        emoji: '🫕',
        description: 'fondue',
        category: 'Food & Drink',
        aliases: ['fondue'],
      },
      {
        emoji: '🥣',
        description: 'bowl with spoon',
        category: 'Food & Drink',
        aliases: ['bowl_with_spoon'],
      },
      {
        emoji: '🥗',
        description: 'green salad',
        category: 'Food & Drink',
        aliases: ['green_salad'],
      },
      {
        emoji: '🍿',
        description: 'popcorn',
        category: 'Food & Drink',
        aliases: ['popcorn'],
      },
      {
        emoji: '🧈',
        description: 'butter',
        category: 'Food & Drink',
        aliases: ['butter'],
      },
      {
        emoji: '🧂',
        description: 'salt',
        category: 'Food & Drink',
        aliases: ['salt'],
      },
      {
        emoji: '🥫',
        description: 'canned food',
        category: 'Food & Drink',
        aliases: ['canned_food'],
      },
      {
        emoji: '🍱',
        description: 'bento box',
        category: 'Food & Drink',
        aliases: ['bento'],
      },
      {
        emoji: '🍘',
        description: 'rice cracker',
        category: 'Food & Drink',
        aliases: ['rice_cracker'],
      },
      {
        emoji: '🍙',
        description: 'rice ball',
        category: 'Food & Drink',
        aliases: ['rice_ball'],
      },
      {
        emoji: '🍚',
        description: 'cooked rice',
        category: 'Food & Drink',
        aliases: ['rice'],
      },
      {
        emoji: '🍛',
        description: 'curry rice',
        category: 'Food & Drink',
        aliases: ['curry'],
      },
      {
        emoji: '🍜',
        description: 'steaming bowl',
        category: 'Food & Drink',
        aliases: ['ramen'],
        tags: ['noodle'],
      },
      {
        emoji: '🍝',
        description: 'spaghetti',
        category: 'Food & Drink',
        aliases: ['spaghetti'],
        tags: ['pasta'],
      },
      {
        emoji: '🍠',
        description: 'roasted sweet potato',
        category: 'Food & Drink',
        aliases: ['sweet_potato'],
      },
      {
        emoji: '🍢',
        description: 'oden',
        category: 'Food & Drink',
        aliases: ['oden'],
      },
      {
        emoji: '🍣',
        description: 'sushi',
        category: 'Food & Drink',
        aliases: ['sushi'],
      },
      {
        emoji: '🍤',
        description: 'fried shrimp',
        category: 'Food & Drink',
        aliases: ['fried_shrimp'],
        tags: ['tempura'],
      },
      {
        emoji: '🍥',
        description: 'fish cake with swirl',
        category: 'Food & Drink',
        aliases: ['fish_cake'],
      },
      {
        emoji: '🥮',
        description: 'moon cake',
        category: 'Food & Drink',
        aliases: ['moon_cake'],
      },
      {
        emoji: '🍡',
        description: 'dango',
        category: 'Food & Drink',
        aliases: ['dango'],
      },
      {
        emoji: '🥟',
        description: 'dumpling',
        category: 'Food & Drink',
        aliases: ['dumpling'],
      },
      {
        emoji: '🥠',
        description: 'fortune cookie',
        category: 'Food & Drink',
        aliases: ['fortune_cookie'],
      },
      {
        emoji: '🥡',
        description: 'takeout box',
        category: 'Food & Drink',
        aliases: ['takeout_box'],
      },
      {
        emoji: '🦀',
        description: 'crab',
        category: 'Food & Drink',
        aliases: ['crab'],
      },
      {
        emoji: '🦞',
        description: 'lobster',
        category: 'Food & Drink',
        aliases: ['lobster'],
      },
      {
        emoji: '🦐',
        description: 'shrimp',
        category: 'Food & Drink',
        aliases: ['shrimp'],
      },
      {
        emoji: '🦑',
        description: 'squid',
        category: 'Food & Drink',
        aliases: ['squid'],
      },
      {
        emoji: '🦪',
        description: 'oyster',
        category: 'Food & Drink',
        aliases: ['oyster'],
      },
      {
        emoji: '🍦',
        description: 'soft ice cream',
        category: 'Food & Drink',
        aliases: ['icecream'],
      },
      {
        emoji: '🍧',
        description: 'shaved ice',
        category: 'Food & Drink',
        aliases: ['shaved_ice'],
      },
      {
        emoji: '🍨',
        description: 'ice cream',
        category: 'Food & Drink',
        aliases: ['ice_cream'],
      },
      {
        emoji: '🍩',
        description: 'doughnut',
        category: 'Food & Drink',
        aliases: ['doughnut'],
      },
      {
        emoji: '🍪',
        description: 'cookie',
        category: 'Food & Drink',
        aliases: ['cookie'],
      },
      {
        emoji: '🎂',
        description: 'birthday cake',
        category: 'Food & Drink',
        aliases: ['birthday'],
        tags: ['party'],
      },
      {
        emoji: '🍰',
        description: 'shortcake',
        category: 'Food & Drink',
        aliases: ['cake'],
        tags: ['dessert'],
      },
      {
        emoji: '🧁',
        description: 'cupcake',
        category: 'Food & Drink',
        aliases: ['cupcake'],
      },
      {
        emoji: '🥧',
        description: 'pie',
        category: 'Food & Drink',
        aliases: ['pie'],
      },
      {
        emoji: '🍫',
        description: 'chocolate bar',
        category: 'Food & Drink',
        aliases: ['chocolate_bar'],
      },
      {
        emoji: '🍬',
        description: 'candy',
        category: 'Food & Drink',
        aliases: ['candy'],
        tags: ['sweet'],
      },
      {
        emoji: '🍭',
        description: 'lollipop',
        category: 'Food & Drink',
        aliases: ['lollipop'],
      },
      {
        emoji: '🍮',
        description: 'custard',
        category: 'Food & Drink',
        aliases: ['custard'],
      },
      {
        emoji: '🍯',
        description: 'honey pot',
        category: 'Food & Drink',
        aliases: ['honey_pot'],
      },
      {
        emoji: '🍼',
        description: 'baby bottle',
        category: 'Food & Drink',
        aliases: ['baby_bottle'],
        tags: ['milk'],
      },
      {
        emoji: '🥛',
        description: 'glass of milk',
        category: 'Food & Drink',
        aliases: ['milk_glass'],
      },
      {
        emoji: '☕',
        description: 'hot beverage',
        category: 'Food & Drink',
        aliases: ['coffee'],
        tags: ['cafe', 'espresso'],
      },
      {
        emoji: '🫖',
        description: 'teapot',
        category: 'Food & Drink',
        aliases: ['teapot'],
      },
      {
        emoji: '🍵',
        description: 'teacup without handle',
        category: 'Food & Drink',
        aliases: ['tea'],
        tags: ['green', 'breakfast'],
      },
      {
        emoji: '🍶',
        description: 'sake',
        category: 'Food & Drink',
        aliases: ['sake'],
      },
      {
        emoji: '🍾',
        description: 'bottle with popping cork',
        category: 'Food & Drink',
        aliases: ['champagne'],
        tags: ['bottle', 'bubbly', 'celebration'],
      },
      {
        emoji: '🍷',
        description: 'wine glass',
        category: 'Food & Drink',
        aliases: ['wine_glass'],
      },
      {
        emoji: '🍸',
        description: 'cocktail glass',
        category: 'Food & Drink',
        aliases: ['cocktail'],
        tags: ['drink'],
      },
      {
        emoji: '🍹',
        description: 'tropical drink',
        category: 'Food & Drink',
        aliases: ['tropical_drink'],
        tags: ['summer', 'vacation'],
      },
      {
        emoji: '🍺',
        description: 'beer mug',
        category: 'Food & Drink',
        aliases: ['beer'],
        tags: ['drink'],
      },
      {
        emoji: '🍻',
        description: 'clinking beer mugs',
        category: 'Food & Drink',
        aliases: ['beers'],
        tags: ['drinks'],
      },
      {
        emoji: '🥂',
        description: 'clinking glasses',
        category: 'Food & Drink',
        aliases: ['clinking_glasses'],
        tags: ['cheers', 'toast'],
      },
      {
        emoji: '🥃',
        description: 'tumbler glass',
        category: 'Food & Drink',
        aliases: ['tumbler_glass'],
        tags: ['whisky'],
      },
      {
        emoji: '🥤',
        description: 'cup with straw',
        category: 'Food & Drink',
        aliases: ['cup_with_straw'],
      },
      {
        emoji: '🧋',
        description: 'bubble tea',
        category: 'Food & Drink',
        aliases: ['bubble_tea'],
      },
      {
        emoji: '🧃',
        description: 'beverage box',
        category: 'Food & Drink',
        aliases: ['beverage_box'],
      },
      {
        emoji: '🧉',
        description: 'mate',
        category: 'Food & Drink',
        aliases: ['mate'],
      },
      {
        emoji: '🧊',
        description: 'ice',
        category: 'Food & Drink',
        aliases: ['ice_cube'],
      },
      {
        emoji: '🥢',
        description: 'chopsticks',
        category: 'Food & Drink',
        aliases: ['chopsticks'],
      },
      {
        emoji: '🍽️',
        description: 'fork and knife with plate',
        category: 'Food & Drink',
        aliases: ['plate_with_cutlery'],
        tags: ['dining', 'dinner'],
      },
      {
        emoji: '🍴',
        description: 'fork and knife',
        category: 'Food & Drink',
        aliases: ['fork_and_knife'],
        tags: ['cutlery'],
      },
      {
        emoji: '🥄',
        description: 'spoon',
        category: 'Food & Drink',
        aliases: ['spoon'],
      },
      {
        emoji: '🔪',
        description: 'kitchen knife',
        category: 'Food & Drink',
        aliases: ['hocho', 'knife'],
        tags: ['cut', 'chop'],
      },
      {
        emoji: '🏺',
        description: 'amphora',
        category: 'Food & Drink',
        aliases: ['amphora'],
      },
];

export default Food;