const Travel = [
    {
        emoji: '🌍',
        description: 'globe showing Europe-Africa',
        category: 'Travel & Places',
        aliases: ['earth_africa'],
        tags: ['globe', 'world', 'international'],
      },
      {
        emoji: '🌎',
        description: 'globe showing Americas',
        category: 'Travel & Places',
        aliases: ['earth_americas'],
        tags: ['globe', 'world', 'international'],
      },
      {
        emoji: '🌏',
        description: 'globe showing Asia-Australia',
        category: 'Travel & Places',
        aliases: ['earth_asia'],
        tags: ['globe', 'world', 'international'],
      },
      {
        emoji: '🌐',
        description: 'globe with meridians',
        category: 'Travel & Places',
        aliases: ['globe_with_meridians'],
        tags: ['world', 'global', 'international'],
      },
      {
        emoji: '🗺️',
        description: 'world map',
        category: 'Travel & Places',
        aliases: ['world_map'],
        tags: ['travel'],
      },
      {
        emoji: '🗾',
        description: 'map of Japan',
        category: 'Travel & Places',
        aliases: ['japan'],
      },
      {
        emoji: '🧭',
        description: 'compass',
        category: 'Travel & Places',
        aliases: ['compass'],
      },
      {
        emoji: '🏔️',
        description: 'snow-capped mountain',
        category: 'Travel & Places',
        aliases: ['mountain_snow'],
      },
      {
        emoji: '⛰️',
        description: 'mountain',
        category: 'Travel & Places',
        aliases: ['mountain'],
      },
      {
        emoji: '🌋',
        description: 'volcano',
        category: 'Travel & Places',
        aliases: ['volcano'],
      },
      {
        emoji: '🗻',
        description: 'mount fuji',
        category: 'Travel & Places',
        aliases: ['mount_fuji'],
      },
      {
        emoji: '🏕️',
        description: 'camping',
        category: 'Travel & Places',
        aliases: ['camping'],
      },
      {
        emoji: '🏖️',
        description: 'beach with umbrella',
        category: 'Travel & Places',
        aliases: ['beach_umbrella'],
      },
      {
        emoji: '🏜️',
        description: 'desert',
        category: 'Travel & Places',
        aliases: ['desert'],
      },
      {
        emoji: '🏝️',
        description: 'desert island',
        category: 'Travel & Places',
        aliases: ['desert_island'],
      },
      {
        emoji: '🏞️',
        description: 'national park',
        category: 'Travel & Places',
        aliases: ['national_park'],
      },
      {
        emoji: '🏟️',
        description: 'stadium',
        category: 'Travel & Places',
        aliases: ['stadium'],
      },
      {
        emoji: '🏛️',
        description: 'classical building',
        category: 'Travel & Places',
        aliases: ['classical_building'],
      },
      {
        emoji: '🏗️',
        description: 'building construction',
        category: 'Travel & Places',
        aliases: ['building_construction'],
      },
      {
        emoji: '🧱',
        description: 'brick',
        category: 'Travel & Places',
        aliases: ['bricks'],
      },
      {
        emoji: '🪨',
        description: 'rock',
        category: 'Travel & Places',
        aliases: ['rock'],
      },
      {
        emoji: '🪵',
        description: 'wood',
        category: 'Travel & Places',
        aliases: ['wood'],
      },
      {
        emoji: '🛖',
        description: 'hut',
        category: 'Travel & Places',
        aliases: ['hut'],
      },
      {
        emoji: '🏘️',
        description: 'houses',
        category: 'Travel & Places',
        aliases: ['houses'],
      },
      {
        emoji: '🏚️',
        description: 'derelict house',
        category: 'Travel & Places',
        aliases: ['derelict_house'],
      },
      {
        emoji: '🏠',
        description: 'house',
        category: 'Travel & Places',
        aliases: ['house'],
      },
      {
        emoji: '🏡',
        description: 'house with garden',
        category: 'Travel & Places',
        aliases: ['house_with_garden'],
      },
      {
        emoji: '🏢',
        description: 'office building',
        category: 'Travel & Places',
        aliases: ['office'],
      },
      {
        emoji: '🏣',
        description: 'Japanese post office',
        category: 'Travel & Places',
        aliases: ['post_office'],
      },
      {
        emoji: '🏤',
        description: 'post office',
        category: 'Travel & Places',
        aliases: ['european_post_office'],
      },
      {
        emoji: '🏥',
        description: 'hospital',
        category: 'Travel & Places',
        aliases: ['hospital'],
      },
      {
        emoji: '🏦',
        description: 'bank',
        category: 'Travel & Places',
        aliases: ['bank'],
      },
      {
        emoji: '🏨',
        description: 'hotel',
        category: 'Travel & Places',
        aliases: ['hotel'],
      },
      {
        emoji: '🏩',
        description: 'love hotel',
        category: 'Travel & Places',
        aliases: ['love_hotel'],
      },
      {
        emoji: '🏪',
        description: 'convenience store',
        category: 'Travel & Places',
        aliases: ['convenience_store'],
      },
      {
        emoji: '🏫',
        description: 'school',
        category: 'Travel & Places',
        aliases: ['school'],
      },
      {
        emoji: '🏬',
        description: 'department store',
        category: 'Travel & Places',
        aliases: ['department_store'],
      },
      {
        emoji: '🏭',
        description: 'factory',
        category: 'Travel & Places',
        aliases: ['factory'],
      },
      {
        emoji: '🏯',
        description: 'Japanese castle',
        category: 'Travel & Places',
        aliases: ['japanese_castle'],
      },
      {
        emoji: '🏰',
        description: 'castle',
        category: 'Travel & Places',
        aliases: ['european_castle'],
      },
      {
        emoji: '💒',
        description: 'wedding',
        category: 'Travel & Places',
        aliases: ['wedding'],
        tags: ['marriage'],
      },
      {
        emoji: '🗼',
        description: 'Tokyo tower',
        category: 'Travel & Places',
        aliases: ['tokyo_tower'],
      },
      {
        emoji: '🗽',
        description: 'Statue of Liberty',
        category: 'Travel & Places',
        aliases: ['statue_of_liberty'],
      },
      {
        emoji: '⛪',
        description: 'church',
        category: 'Travel & Places',
        aliases: ['church'],
      },
      {
        emoji: '🕌',
        description: 'mosque',
        category: 'Travel & Places',
        aliases: ['mosque'],
      },
      {
        emoji: '🛕',
        description: 'hindu temple',
        category: 'Travel & Places',
        aliases: ['hindu_temple'],
      },
      {
        emoji: '🕍',
        description: 'synagogue',
        category: 'Travel & Places',
        aliases: ['synagogue'],
      },
      {
        emoji: '⛩️',
        description: 'shinto shrine',
        category: 'Travel & Places',
        aliases: ['shinto_shrine'],
      },
      {
        emoji: '🕋',
        description: 'kaaba',
        category: 'Travel & Places',
        aliases: ['kaaba'],
      },
      {
        emoji: '⛲',
        description: 'fountain',
        category: 'Travel & Places',
        aliases: ['fountain'],
      },
      {
        emoji: '⛺',
        description: 'tent',
        category: 'Travel & Places',
        aliases: ['tent'],
        tags: ['camping'],
      },
      {
        emoji: '🌁',
        description: 'foggy',
        category: 'Travel & Places',
        aliases: ['foggy'],
        tags: ['karl'],
      },
      {
        emoji: '🌃',
        description: 'night with stars',
        category: 'Travel & Places',
        aliases: ['night_with_stars'],
      },
      {
        emoji: '🏙️',
        description: 'cityscape',
        category: 'Travel & Places',
        aliases: ['cityscape'],
        tags: ['skyline'],
      },
      {
        emoji: '🌄',
        description: 'sunrise over mountains',
        category: 'Travel & Places',
        aliases: ['sunrise_over_mountains'],
      },
      {
        emoji: '🌅',
        description: 'sunrise',
        category: 'Travel & Places',
        aliases: ['sunrise'],
      },
      {
        emoji: '🌆',
        description: 'cityscape at dusk',
        category: 'Travel & Places',
        aliases: ['city_sunset'],
      },
      {
        emoji: '🌇',
        description: 'sunset',
        category: 'Travel & Places',
        aliases: ['city_sunrise'],
      },
      {
        emoji: '🌉',
        description: 'bridge at night',
        category: 'Travel & Places',
        aliases: ['bridge_at_night'],
      },
      {
        emoji: '♨️',
        description: 'hot springs',
        category: 'Travel & Places',
        aliases: ['hotsprings'],
      },
      {
        emoji: '🎠',
        description: 'carousel horse',
        category: 'Travel & Places',
        aliases: ['carousel_horse'],
      },
      {
        emoji: '🎡',
        description: 'ferris wheel',
        category: 'Travel & Places',
        aliases: ['ferris_wheel'],
      },
      {
        emoji: '🎢',
        description: 'roller coaster',
        category: 'Travel & Places',
        aliases: ['roller_coaster'],
      },
      {
        emoji: '💈',
        description: 'barber pole',
        category: 'Travel & Places',
        aliases: ['barber'],
      },
      {
        emoji: '🎪',
        description: 'circus tent',
        category: 'Travel & Places',
        aliases: ['circus_tent'],
      },
      {
        emoji: '🚂',
        description: 'locomotive',
        category: 'Travel & Places',
        aliases: ['steam_locomotive'],
        tags: ['train'],
      },
      {
        emoji: '🚃',
        description: 'railway car',
        category: 'Travel & Places',
        aliases: ['railway_car'],
      },
      {
        emoji: '🚄',
        description: 'high-speed train',
        category: 'Travel & Places',
        aliases: ['bullettrain_side'],
        tags: ['train'],
      },
      {
        emoji: '🚅',
        description: 'bullet train',
        category: 'Travel & Places',
        aliases: ['bullettrain_front'],
        tags: ['train'],
      },
      {
        emoji: '🚆',
        description: 'train',
        category: 'Travel & Places',
        aliases: ['train2'],
      },
      {
        emoji: '🚇',
        description: 'metro',
        category: 'Travel & Places',
        aliases: ['metro'],
      },
      {
        emoji: '🚈',
        description: 'light rail',
        category: 'Travel & Places',
        aliases: ['light_rail'],
      },
      {
        emoji: '🚉',
        description: 'station',
        category: 'Travel & Places',
        aliases: ['station'],
      },
      {
        emoji: '🚊',
        description: 'tram',
        category: 'Travel & Places',
        aliases: ['tram'],
      },
      {
        emoji: '🚝',
        description: 'monorail',
        category: 'Travel & Places',
        aliases: ['monorail'],
      },
      {
        emoji: '🚞',
        description: 'mountain railway',
        category: 'Travel & Places',
        aliases: ['mountain_railway'],
      },
      {
        emoji: '🚋',
        description: 'tram car',
        category: 'Travel & Places',
        aliases: ['train'],
      },
      {
        emoji: '🚌',
        description: 'bus',
        category: 'Travel & Places',
        aliases: ['bus'],
      },
      {
        emoji: '🚍',
        description: 'oncoming bus',
        category: 'Travel & Places',
        aliases: ['oncoming_bus'],
      },
      {
        emoji: '🚎',
        description: 'trolleybus',
        category: 'Travel & Places',
        aliases: ['trolleybus'],
      },
      {
        emoji: '🚐',
        description: 'minibus',
        category: 'Travel & Places',
        aliases: ['minibus'],
      },
      {
        emoji: '🚑',
        description: 'ambulance',
        category: 'Travel & Places',
        aliases: ['ambulance'],
      },
      {
        emoji: '🚒',
        description: 'fire engine',
        category: 'Travel & Places',
        aliases: ['fire_engine'],
      },
      {
        emoji: '🚓',
        description: 'police car',
        category: 'Travel & Places',
        aliases: ['police_car'],
      },
      {
        emoji: '🚔',
        description: 'oncoming police car',
        category: 'Travel & Places',
        aliases: ['oncoming_police_car'],
      },
      {
        emoji: '🚕',
        description: 'taxi',
        category: 'Travel & Places',
        aliases: ['taxi'],
      },
      {
        emoji: '🚖',
        description: 'oncoming taxi',
        category: 'Travel & Places',
        aliases: ['oncoming_taxi'],
      },
      {
        emoji: '🚗',
        description: 'automobile',
        category: 'Travel & Places',
        aliases: ['car', 'red_car'],
      },
      {
        emoji: '🚘',
        description: 'oncoming automobile',
        category: 'Travel & Places',
        aliases: ['oncoming_automobile'],
      },
      {
        emoji: '🚙',
        description: 'sport utility vehicle',
        category: 'Travel & Places',
        aliases: ['blue_car'],
      },
      {
        emoji: '🛻',
        description: 'pickup truck',
        category: 'Travel & Places',
        aliases: ['pickup_truck'],
      },
      {
        emoji: '🚚',
        description: 'delivery truck',
        category: 'Travel & Places',
        aliases: ['truck'],
      },
      {
        emoji: '🚛',
        description: 'articulated lorry',
        category: 'Travel & Places',
        aliases: ['articulated_lorry'],
      },
      {
        emoji: '🚜',
        description: 'tractor',
        category: 'Travel & Places',
        aliases: ['tractor'],
      },
      {
        emoji: '🏎️',
        description: 'racing car',
        category: 'Travel & Places',
        aliases: ['racing_car'],
      },
      {
        emoji: '🏍️',
        description: 'motorcycle',
        category: 'Travel & Places',
        aliases: ['motorcycle'],
      },
      {
        emoji: '🛵',
        description: 'motor scooter',
        category: 'Travel & Places',
        aliases: ['motor_scooter'],
      },
      {
        emoji: '🦽',
        description: 'manual wheelchair',
        category: 'Travel & Places',
        aliases: ['manual_wheelchair'],
      },
      {
        emoji: '🦼',
        description: 'motorized wheelchair',
        category: 'Travel & Places',
        aliases: ['motorized_wheelchair'],
      },
      {
        emoji: '🛺',
        description: 'auto rickshaw',
        category: 'Travel & Places',
        aliases: ['auto_rickshaw'],
      },
      {
        emoji: '🚲',
        description: 'bicycle',
        category: 'Travel & Places',
        aliases: ['bike'],
        tags: ['bicycle'],
      },
      {
        emoji: '🛴',
        description: 'kick scooter',
        category: 'Travel & Places',
        aliases: ['kick_scooter'],
      },
      {
        emoji: '🛹',
        description: 'skateboard',
        category: 'Travel & Places',
        aliases: ['skateboard'],
      },
      {
        emoji: '🛼',
        description: 'roller skate',
        category: 'Travel & Places',
        aliases: ['roller_skate'],
      },
      {
        emoji: '🚏',
        description: 'bus stop',
        category: 'Travel & Places',
        aliases: ['busstop'],
      },
      {
        emoji: '🛣️',
        description: 'motorway',
        category: 'Travel & Places',
        aliases: ['motorway'],
      },
      {
        emoji: '🛤️',
        description: 'railway track',
        category: 'Travel & Places',
        aliases: ['railway_track'],
      },
      {
        emoji: '🛢️',
        description: 'oil drum',
        category: 'Travel & Places',
        aliases: ['oil_drum'],
      },
      {
        emoji: '⛽',
        description: 'fuel pump',
        category: 'Travel & Places',
        aliases: ['fuelpump'],
      },
      {
        emoji: '🚨',
        description: 'police car light',
        category: 'Travel & Places',
        aliases: ['rotating_light'],
        tags: ['911', 'emergency'],
      },
      {
        emoji: '🚥',
        description: 'horizontal traffic light',
        category: 'Travel & Places',
        aliases: ['traffic_light'],
      },
      {
        emoji: '🚦',
        description: 'vertical traffic light',
        category: 'Travel & Places',
        aliases: ['vertical_traffic_light'],
        tags: ['semaphore'],
      },
      {
        emoji: '🛑',
        description: 'stop sign',
        category: 'Travel & Places',
        aliases: ['stop_sign'],
      },
      {
        emoji: '🚧',
        description: 'construction',
        category: 'Travel & Places',
        aliases: ['construction'],
        tags: ['wip'],
      },
      {
        emoji: '⚓',
        description: 'anchor',
        category: 'Travel & Places',
        aliases: ['anchor'],
        tags: ['ship'],
      },
      {
        emoji: '⛵',
        description: 'sailboat',
        category: 'Travel & Places',
        aliases: ['boat', 'sailboat'],
      },
      {
        emoji: '🛶',
        description: 'canoe',
        category: 'Travel & Places',
        aliases: ['canoe'],
      },
      {
        emoji: '🚤',
        description: 'speedboat',
        category: 'Travel & Places',
        aliases: ['speedboat'],
        tags: ['ship'],
      },
      {
        emoji: '🛳️',
        description: 'passenger ship',
        category: 'Travel & Places',
        aliases: ['passenger_ship'],
        tags: ['cruise'],
      },
      {
        emoji: '⛴️',
        description: 'ferry',
        category: 'Travel & Places',
        aliases: ['ferry'],
      },
      {
        emoji: '🛥️',
        description: 'motor boat',
        category: 'Travel & Places',
        aliases: ['motor_boat'],
      },
      {
        emoji: '🚢',
        description: 'ship',
        category: 'Travel & Places',
        aliases: ['ship'],
      },
      {
        emoji: '✈️',
        description: 'airplane',
        category: 'Travel & Places',
        aliases: ['airplane'],
        tags: ['flight'],
      },
      {
        emoji: '🛩️',
        description: 'small airplane',
        category: 'Travel & Places',
        aliases: ['small_airplane'],
        tags: ['flight'],
      },
      {
        emoji: '🛫',
        description: 'airplane departure',
        category: 'Travel & Places',
        aliases: ['flight_departure'],
      },
      {
        emoji: '🛬',
        description: 'airplane arrival',
        category: 'Travel & Places',
        aliases: ['flight_arrival'],
      },
      {
        emoji: '🪂',
        description: 'parachute',
        category: 'Travel & Places',
        aliases: ['parachute'],
      },
      {
        emoji: '💺',
        description: 'seat',
        category: 'Travel & Places',
        aliases: ['seat'],
      },
      {
        emoji: '🚁',
        description: 'helicopter',
        category: 'Travel & Places',
        aliases: ['helicopter'],
      },
      {
        emoji: '🚟',
        description: 'suspension railway',
        category: 'Travel & Places',
        aliases: ['suspension_railway'],
      },
      {
        emoji: '🚠',
        description: 'mountain cableway',
        category: 'Travel & Places',
        aliases: ['mountain_cableway'],
      },
      {
        emoji: '🚡',
        description: 'aerial tramway',
        category: 'Travel & Places',
        aliases: ['aerial_tramway'],
      },
      {
        emoji: '🛰️',
        description: 'satellite',
        category: 'Travel & Places',
        aliases: ['artificial_satellite'],
        tags: ['orbit', 'space'],
      },
      {
        emoji: '🚀',
        description: 'rocket',
        category: 'Travel & Places',
        aliases: ['rocket'],
        tags: ['ship', 'launch'],
      },
      {
        emoji: '🛸',
        description: 'flying saucer',
        category: 'Travel & Places',
        aliases: ['flying_saucer'],
        tags: ['ufo'],
      },
      {
        emoji: '🛎️',
        description: 'bellhop bell',
        category: 'Travel & Places',
        aliases: ['bellhop_bell'],
      },
      {
        emoji: '🧳',
        description: 'luggage',
        category: 'Travel & Places',
        aliases: ['luggage'],
      },
      {
        emoji: '⌛',
        description: 'hourglass done',
        category: 'Travel & Places',
        aliases: ['hourglass'],
        tags: ['time'],
      },
      {
        emoji: '⏳',
        description: 'hourglass not done',
        category: 'Travel & Places',
        aliases: ['hourglass_flowing_sand'],
        tags: ['time'],
      },
      {
        emoji: '⌚',
        description: 'watch',
        category: 'Travel & Places',
        aliases: ['watch'],
        tags: ['time'],
      },
      {
        emoji: '⏰',
        description: 'alarm clock',
        category: 'Travel & Places',
        aliases: ['alarm_clock'],
        tags: ['morning'],
      },
      {
        emoji: '⏱️',
        description: 'stopwatch',
        category: 'Travel & Places',
        aliases: ['stopwatch'],
      },
      {
        emoji: '⏲️',
        description: 'timer clock',
        category: 'Travel & Places',
        aliases: ['timer_clock'],
      },
      {
        emoji: '🕰️',
        description: 'mantelpiece clock',
        category: 'Travel & Places',
        aliases: ['mantelpiece_clock'],
      },
      {
        emoji: '🕛',
        description: 'twelve o’clock',
        category: 'Travel & Places',
        aliases: ['clock12'],
      },
      {
        emoji: '🕧',
        description: 'twelve-thirty',
        category: 'Travel & Places',
        aliases: ['clock1230'],
      },
      {
        emoji: '🕐',
        description: 'one o’clock',
        category: 'Travel & Places',
        aliases: ['clock1'],
      },
      {
        emoji: '🕜',
        description: 'one-thirty',
        category: 'Travel & Places',
        aliases: ['clock130'],
      },
      {
        emoji: '🕑',
        description: 'two o’clock',
        category: 'Travel & Places',
        aliases: ['clock2'],
      },
      {
        emoji: '🕝',
        description: 'two-thirty',
        category: 'Travel & Places',
        aliases: ['clock230'],
      },
      {
        emoji: '🕒',
        description: 'three o’clock',
        category: 'Travel & Places',
        aliases: ['clock3'],
      },
      {
        emoji: '🕞',
        description: 'three-thirty',
        category: 'Travel & Places',
        aliases: ['clock330'],
      },
      {
        emoji: '🕓',
        description: 'four o’clock',
        category: 'Travel & Places',
        aliases: ['clock4'],
      },
      {
        emoji: '🕟',
        description: 'four-thirty',
        category: 'Travel & Places',
        aliases: ['clock430'],
      },
      {
        emoji: '🕔',
        description: 'five o’clock',
        category: 'Travel & Places',
        aliases: ['clock5'],
      },
      {
        emoji: '🕠',
        description: 'five-thirty',
        category: 'Travel & Places',
        aliases: ['clock530'],
      },
      {
        emoji: '🕕',
        description: 'six o’clock',
        category: 'Travel & Places',
        aliases: ['clock6'],
      },
      {
        emoji: '🕡',
        description: 'six-thirty',
        category: 'Travel & Places',
        aliases: ['clock630'],
      },
      {
        emoji: '🕖',
        description: 'seven o’clock',
        category: 'Travel & Places',
        aliases: ['clock7'],
      },
      {
        emoji: '🕢',
        description: 'seven-thirty',
        category: 'Travel & Places',
        aliases: ['clock730'],
      },
      {
        emoji: '🕗',
        description: 'eight o’clock',
        category: 'Travel & Places',
        aliases: ['clock8'],
      },
      {
        emoji: '🕣',
        description: 'eight-thirty',
        category: 'Travel & Places',
        aliases: ['clock830'],
      },
      {
        emoji: '🕘',
        description: 'nine o’clock',
        category: 'Travel & Places',
        aliases: ['clock9'],
      },
      {
        emoji: '🕤',
        description: 'nine-thirty',
        category: 'Travel & Places',
        aliases: ['clock930'],
      },
      {
        emoji: '🕙',
        description: 'ten o’clock',
        category: 'Travel & Places',
        aliases: ['clock10'],
      },
      {
        emoji: '🕥',
        description: 'ten-thirty',
        category: 'Travel & Places',
        aliases: ['clock1030'],
      },
      {
        emoji: '🕚',
        description: 'eleven o’clock',
        category: 'Travel & Places',
        aliases: ['clock11'],
      },
      {
        emoji: '🕦',
        description: 'eleven-thirty',
        category: 'Travel & Places',
        aliases: ['clock1130'],
      },
      {
        emoji: '🌑',
        description: 'new moon',
        category: 'Travel & Places',
        aliases: ['new_moon'],
      },
      {
        emoji: '🌒',
        description: 'waxing crescent moon',
        category: 'Travel & Places',
        aliases: ['waxing_crescent_moon'],
      },
      {
        emoji: '🌓',
        description: 'first quarter moon',
        category: 'Travel & Places',
        aliases: ['first_quarter_moon'],
      },
      {
        emoji: '🌔',
        description: 'waxing gibbous moon',
        category: 'Travel & Places',
        aliases: ['moon', 'waxing_gibbous_moon'],
      },
      {
        emoji: '🌕',
        description: 'full moon',
        category: 'Travel & Places',
        aliases: ['full_moon'],
      },
      {
        emoji: '🌖',
        description: 'waning gibbous moon',
        category: 'Travel & Places',
        aliases: ['waning_gibbous_moon'],
      },
      {
        emoji: '🌗',
        description: 'last quarter moon',
        category: 'Travel & Places',
        aliases: ['last_quarter_moon'],
      },
      {
        emoji: '🌘',
        description: 'waning crescent moon',
        category: 'Travel & Places',
        aliases: ['waning_crescent_moon'],
      },
      {
        emoji: '🌙',
        description: 'crescent moon',
        category: 'Travel & Places',
        aliases: ['crescent_moon'],
        tags: ['night'],
      },
      {
        emoji: '🌚',
        description: 'new moon face',
        category: 'Travel & Places',
        aliases: ['new_moon_with_face'],
      },
      {
        emoji: '🌛',
        description: 'first quarter moon face',
        category: 'Travel & Places',
        aliases: ['first_quarter_moon_with_face'],
      },
      {
        emoji: '🌜',
        description: 'last quarter moon face',
        category: 'Travel & Places',
        aliases: ['last_quarter_moon_with_face'],
      },
      {
        emoji: '🌡️',
        description: 'thermometer',
        category: 'Travel & Places',
        aliases: ['thermometer'],
      },
      {
        emoji: '☀️',
        description: 'sun',
        category: 'Travel & Places',
        aliases: ['sunny'],
        tags: ['weather'],
      },
      {
        emoji: '🌝',
        description: 'full moon face',
        category: 'Travel & Places',
        aliases: ['full_moon_with_face'],
      },
      {
        emoji: '🌞',
        description: 'sun with face',
        category: 'Travel & Places',
        aliases: ['sun_with_face'],
        tags: ['summer'],
      },
      {
        emoji: '🪐',
        description: 'ringed planet',
        category: 'Travel & Places',
        aliases: ['ringed_planet'],
      },
      {
        emoji: '⭐',
        description: 'star',
        category: 'Travel & Places',
        aliases: ['star'],
      },
      {
        emoji: '🌟',
        description: 'glowing star',
        category: 'Travel & Places',
        aliases: ['star2'],
      },
      {
        emoji: '🌠',
        description: 'shooting star',
        category: 'Travel & Places',
        aliases: ['stars'],
      },
      {
        emoji: '🌌',
        description: 'milky way',
        category: 'Travel & Places',
        aliases: ['milky_way'],
      },
      {
        emoji: '☁️',
        description: 'cloud',
        category: 'Travel & Places',
        aliases: ['cloud'],
      },
      {
        emoji: '⛅',
        description: 'sun behind cloud',
        category: 'Travel & Places',
        aliases: ['partly_sunny'],
        tags: ['weather', 'cloud'],
      },
      {
        emoji: '⛈️',
        description: 'cloud with lightning and rain',
        category: 'Travel & Places',
        aliases: ['cloud_with_lightning_and_rain'],
      },
      {
        emoji: '🌤️',
        description: 'sun behind small cloud',
        category: 'Travel & Places',
        aliases: ['sun_behind_small_cloud'],
      },
      {
        emoji: '🌥️',
        description: 'sun behind large cloud',
        category: 'Travel & Places',
        aliases: ['sun_behind_large_cloud'],
      },
      {
        emoji: '🌦️',
        description: 'sun behind rain cloud',
        category: 'Travel & Places',
        aliases: ['sun_behind_rain_cloud'],
      },
      {
        emoji: '🌧️',
        description: 'cloud with rain',
        category: 'Travel & Places',
        aliases: ['cloud_with_rain'],
      },
      {
        emoji: '🌨️',
        description: 'cloud with snow',
        category: 'Travel & Places',
        aliases: ['cloud_with_snow'],
      },
      {
        emoji: '🌩️',
        description: 'cloud with lightning',
        category: 'Travel & Places',
        aliases: ['cloud_with_lightning'],
      },
      {
        emoji: '🌪️',
        description: 'tornado',
        category: 'Travel & Places',
        aliases: ['tornado'],
      },
      {
        emoji: '🌫️',
        description: 'fog',
        category: 'Travel & Places',
        aliases: ['fog'],
      },
      {
        emoji: '🌬️',
        description: 'wind face',
        category: 'Travel & Places',
        aliases: ['wind_face'],
      },
      {
        emoji: '🌀',
        description: 'cyclone',
        category: 'Travel & Places',
        aliases: ['cyclone'],
        tags: ['swirl'],
      },
      {
        emoji: '🌈',
        description: 'rainbow',
        category: 'Travel & Places',
        aliases: ['rainbow'],
      },
      {
        emoji: '🌂',
        description: 'closed umbrella',
        category: 'Travel & Places',
        aliases: ['closed_umbrella'],
        tags: ['weather', 'rain'],
      },
      {
        emoji: '☂️',
        description: 'umbrella',
        category: 'Travel & Places',
        aliases: ['open_umbrella'],
      },
      {
        emoji: '☔',
        description: 'umbrella with rain drops',
        category: 'Travel & Places',
        aliases: ['umbrella'],
        tags: ['rain', 'weather'],
      },
      {
        emoji: '⛱️',
        description: 'umbrella on ground',
        category: 'Travel & Places',
        aliases: ['parasol_on_ground'],
        tags: ['beach_umbrella'],
      },
      {
        emoji: '⚡',
        description: 'high voltage',
        category: 'Travel & Places',
        aliases: ['zap'],
        tags: ['lightning', 'thunder'],
      },
      {
        emoji: '❄️',
        description: 'snowflake',
        category: 'Travel & Places',
        aliases: ['snowflake'],
        tags: ['winter', 'cold', 'weather'],
      },
      {
        emoji: '☃️',
        description: 'snowman',
        category: 'Travel & Places',
        aliases: ['snowman_with_snow'],
        tags: ['winter', 'christmas'],
      },
      {
        emoji: '⛄',
        description: 'snowman without snow',
        category: 'Travel & Places',
        aliases: ['snowman'],
        tags: ['winter'],
      },
      {
        emoji: '☄️',
        description: 'comet',
        category: 'Travel & Places',
        aliases: ['comet'],
      },
      {
        emoji: '🔥',
        description: 'fire',
        category: 'Travel & Places',
        aliases: ['fire'],
        tags: ['burn'],
      },
      {
        emoji: '💧',
        description: 'droplet',
        category: 'Travel & Places',
        aliases: ['droplet'],
        tags: ['water'],
      },
      {
        emoji: '🌊',
        description: 'water wave',
        category: 'Travel & Places',
        aliases: ['ocean'],
        tags: ['sea'],
      },
];

export default Travel;